# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee7ac29d0ae7a12c6d9610dd680dd1a63d9bc333a428be29ac7fc7d9353dfb73045382c01a09a94d5ec4c99e55ce0f5d8f05ff949f14bc05f02f2993cfb1a7b5

test:
  secret_key_base: fa6c3edf255b51c9cda7f0a50ac02689c2d799be37cc9b929b99da0a79398d7ed757283395feb063a4d10c2a9e35248a784b2e18d29a7555844632e549ef3a7f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
